apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNtbDBlbTFoZEdobGR6b3dTR05KV1c4NUpBPT0iCgkJfQoJfSwKCSJjcmVkSGVscGVycyI6IHsKCQkiYXNpYS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiZXUuZ2NyLmlvIjogImdjbG91ZCIsCgkJImdjci5pbyI6ICJnY2xvdWQiLAoJCSJtYXJrZXRwbGFjZS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkic3RhZ2luZy1rOHMuZ2NyLmlvIjogImdjbG91ZCIsCgkJInVzLmdjci5pbyI6ICJnY2xvdWQiCgl9Cn0=
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  SA_PASSWORD: VXAyMm1sRkY=
kind: Secret
metadata:
  name: mssql
type: Opaque
