apiVersion: apps/v1
kind: Deployment
metadata:
  name: lfkwebapp-deployment
spec:
  selector:
    matchLabels:
      app: lfkwebapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lfkwebapp
    spec:
      containers:
      - name: lfkwebapp
        image: ritzmathew/lfk:lfkwebapp-stag-v1.0.6
        env:
        - name: SqlConnectionString
          value: "Server=lfksqlsrv-service.default.svc,1433;Initial Catalog=school;Persist Security Info=False;User ID=sa;Password=Up22mlFF;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" 
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: lfkwebapp-service
  labels:
    app: lfkwebapp-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32185
  selector:
    app: lfkwebapp
  sessionAffinity: None