apiVersion: apps/v1
kind: Deployment
metadata:
  name: lfkwebapp-deployment
spec:
  selector:
    matchLabels:
      app: lfkwebapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lfkwebapp
    spec:
      containers:
      - name: lfkwebapp
        image: ritzmathew/lfk:latest
        env:
        - name: SqlConnectionString
          valueFrom:
            secretKeyRef:
              name: mssqlcon
              key: ConnectionString
        ports:
        - containerPort: 443
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: lfkwebapp-service
  labels:
    app: lfkwebapp-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 32185
  selector:
    app: lfkwebapp
  sessionAffinity: None