# This is a basic workflow to help you get started with Actions

name: LittleFlowerKalewadi CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Hub login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} 
        run: | 
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      # Runs a set of commands using the runners shell
      - name: Docker build lfkwebapp
        run: |
          docker build ./LittleFlowerKalewadi -t lfk/webapp:stag-v1.0.5

      # Push image to Docker Hub    
      - name: Docker push lfkwebapp
        run: |
          docker tag lfk/webapp:stag-v1.0.5 $DOCKERHUB_USERNAME/lfk/lfkwebapp:stag-v1.0.5
          docker push $DOCKERHUB_USERNAME/lfk/lfkwebapp:stag-v1.0.5
